### ISSUE TITLE
Errors in test results

### ISSUE THREAD

**Issue by KELs7** [xian-network/dice-game#1]
This is the logs when I run `python test_dice.py` in xian_venv .
```
2024-04-21 08:51:35,538 - DEBUG - Creating converter from 3 to 5
2024-04-21 08:51:35,548 - DEBUG - Creating converter from 5 to 3
/usr/lib/python3.11/ast.py:418: DeprecationWarning: visit_Num is deprecated; add visit_Constant
  return visitor(node)
2024-04-21 08:51:35,595 - ERROR - Token not allowed
2024-04-21 08:51:35,595 - ERROR - Traceback (most recent call last):
  File "/home/kels/Desktop/DEV/github/contracting/contracting/execution/executor.py", line 126, in execute
    result = func(**kwargs)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "", line 22, in roll
AssertionError: Token not allowed

..2024-04-21 08:51:35,713 - ERROR - Bet size exceeds the maximum allowed bet
2024-04-21 08:51:35,713 - ERROR - Traceback (most recent call last):
  File "/home/kels/Desktop/DEV/github/contracting/contracting/execution/executor.py", line 126, in execute
    result = func(**kwargs)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "", line 23, in roll
AssertionError: Bet size exceeds the maximum allowed bet

....2024-04-21 08:51:35,951 - ERROR - Contract does not have enough funds to cover the bet
2024-04-21 08:51:35,952 - ERROR - Traceback (most recent call last):
  File "/home/kels/Desktop/DEV/github/contracting/contracting/execution/executor.py", line 126, in execute
    result = func(**kwargs)
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "", line 37, in roll
AssertionError: Contract does not have enough funds to cover the bet

.
----------------------------------------------------------------------
Ran 7 tests in 0.416s

OK
```

**Comment by crosschainer** [comment]
this is expected behaviours and tests succeed since they are triggering the errors

**Comment by KELs7** [comment]
Turns out these were expected results so closing issue
